CREATE TABLE [dbo].[PatientClinicalHistories] (
    [Id]                               INT            IDENTITY (1, 1) NOT NULL,
    [PatientId]                        INT            NOT NULL,
    [CreatedAt]                        DATETIME2 (7)  NOT NULL,
    [LastUpdatedAt]                    DATETIME2 (7)  NULL,
    [LastUpdatedByPsychologistId]      INT            NULL,
    [Lacerations]                      NVARCHAR (MAX) NULL,
    [Hematomas]                        NVARCHAR (MAX) NULL,
    [Burns]                            NVARCHAR (MAX) NULL,
    [Scars]                            NVARCHAR (MAX) NULL,
    [Fractures]                        NVARCHAR (MAX) NULL,
    [PhysicalObservations]             NVARCHAR (MAX) NULL,
    [CognitiveDisability]              NVARCHAR (MAX) NULL,
    [Epilepsy]                         NVARCHAR (MAX) NULL,
    [HereditaryFamilyDiseases]         NVARCHAR (MAX) NULL,
    [PsychoactiveSubstanceConsumption] NVARCHAR (MAX) NULL,
    [AlcoholConsumption]               NVARCHAR (MAX) NULL,
    [MentalHealthDiagnosis]            NVARCHAR (MAX) NULL,
    [SuicideAttempts]                  NVARCHAR (MAX) NULL,
    [TraumaticEvents]                  NVARCHAR (MAX) NULL,
    [IsMedicated]                      NVARCHAR (MAX) NULL,
    [SelfHarmHistory]                  NVARCHAR (MAX) NULL,
    [PsychiatricHospitalizations]      NVARCHAR (MAX) NULL,
    [MentalHealthObservations]         NVARCHAR (MAX) NULL,
    [SchoolEntryAge]                   NVARCHAR (MAX) NULL,
    [InitialAdaptation]                NVARCHAR (MAX) NULL,
    [AcademicPerformance]              NVARCHAR (MAX) NULL,
    [LostYears]                        NVARCHAR (MAX) NULL,
    [CurrentGrade]                     NVARCHAR (MAX) NULL,
    [EasyAndDifficultSubjects]         NVARCHAR (MAX) NULL,
    [DailyStudyTimeHours]              NVARCHAR (MAX) NULL,
    [FamilyEnvironmentRelated]         NVARCHAR (MAX) NULL,
    [SocialEnvironmentRelated]         NVARCHAR (MAX) NULL,
    [AcademicEnvironmentRelated]       NVARCHAR (MAX) NULL,
    [IndividualCharacteristicsRelated] NVARCHAR (MAX) NULL,
    [DevelopmentAge]                   NVARCHAR (MAX) NULL,
    [SexualIdentity]                   NVARCHAR (MAX) NULL,
    [SexualOrientation]                NVARCHAR (MAX) NULL,
    [AgeOfFirstSexualIntercourse]      NVARCHAR (MAX) NULL,
    [FamilyPlanningMethodsUse]         NVARCHAR (MAX) NULL,
    [HasBeenSexuallyAbused]            NVARCHAR (MAX) NULL,
    [SexuallyTransmittedDiseases]      NVARCHAR (MAX) NULL,
    [TeenageParent]                    NVARCHAR (MAX) NULL,
    [ConsciousnessLevel]               NVARCHAR (MAX) NULL,
    [Attention]                        NVARCHAR (MAX) NULL,
    [SensoryPerception]                NVARCHAR (MAX) NULL,
    [Affect]                           NVARCHAR (MAX) NULL,
    [Language]                         NVARCHAR (MAX) NULL,
    [Orientation]                      NVARCHAR (MAX) NULL,
    [Sleep]                            NVARCHAR (MAX) NULL,
    [Thought]                          NVARCHAR (MAX) NULL,
    [MotorConduct]                     NVARCHAR (MAX) NULL,
    [Memory]                           NVARCHAR (MAX) NULL,
    [FeedingPattern]                   NVARCHAR (MAX) NULL,
    [Intelligence]                     NVARCHAR (MAX) NULL,
    [ReasoningLevel]                   NVARCHAR (MAX) NULL,
    [PostureAndAttitude]               NVARCHAR (MAX) NULL,
    [Analysis]                         NVARCHAR (MAX) NULL,
    [MainDiagnosis]                    NVARCHAR (MAX) NULL,
    [TreatmentPlan]                    NVARCHAR (MAX) NULL,
    [Objectives]                       NVARCHAR (MAX) NULL,
    [Recommendations]                  NVARCHAR (MAX) NULL,
    [Commitments]                      NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_PatientClinicalHistories] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PatientClinicalHistories_Patients_PatientId] FOREIGN KEY ([PatientId]) REFERENCES [dbo].[Patients] ([Id]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_PatientClinicalHistories_PatientId]
    ON [dbo].[PatientClinicalHistories]([PatientId] ASC);

